### ISSUE TITLE
Is it possible to use Version Catalog while defining plugins in Convention Plugins?

### ISSUE THREAD

**Issue by Kacper86** [erichaagdev/erichaag.dev#31]
Hi!

Thank you very much for such a useful article! I believe it should be included in the official Gradle documentation :)

I have just one question - is it possible to use Version Catalog while defining plugins in Convention Plugins?

As I noticed that the code snippets in your article do not facilitate Version Catalog to specify plugin versions. 

I tried to do the following in my convention.gradle file:

```
plugins {
    alias(libs.plugins.jacocoPlugin)
}
```

But it caused an error:

```
 only alias(libs.plugins.someAlias) plugin identifiers where `libs` is a valid version catalog
  
  For more information on the plugins {} block, please refer to https://docs.gradle.org/8.9/userguide/plugins.html#sec:plugins_block in the Gradle documentation.
  
   @ line 2, column 5.
         alias(libs.plugins.jacocoPlugin)
         ^
  
  1 error
```

If it's not possible, maybe it would be possible to add such remark to the article? That would be very helpful as well!

Thank you for help!

**Comment by erichaagdev** [comment]
Hi, @Kacper86! 👋

Thank you greatly for the kind words about my article. 😊

Unfortunately, it's not possible to use version catalog type-safe accessors within precompiled script plugins. 

Actually, this is currently [the most requested Gradle feature](https://github.com/gradle/gradle/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). 

Please give this issue a 👍: https://github.com/gradle/gradle/issues/15383

You bring up a good point about mentioning it in the article. I'll consider that.

Thanks again!

**Comment by Kacper86** [comment]
Hi @erichaagdev ,

I see, thank you for a quick response!

I have a 👍 to https://github.com/gradle/gradle/issues/15383 :)

Have a great day!
